apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llmadapter.fullname" . }}-env
  namespace: {{ template "llmadapter.namespace" . }}
  labels:
    {{- include "llmadapter.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |
    AWS_ACCESS_KEY_ID={{ .Values.config.env.awsAccessKeyId | quote }}
    AWS_SECRET_ACCESS_KEY={{ .Values.config.env.awsSecretAccessKey | quote }}
    BUCKET_NAME={{ .Values.config.env.bucketName | quote }}