apiVersion: v1
kind: Service
metadata:
  name: {{ include "docsconverter.fullname" . }}
  namespace: {{ include "docsconverter.namespace" . }}
  labels:
    {{- include "docsconverter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "docsconverter.selectorLabels" . | nindent 4 }} 