{{- /*
Create Configmaps from templates
*/}}

{{- include "assistos.configmap-bdns" (list $ . "" (dict)) }}
---
{{- include "assistos.configmap-domains" (list $ . "" (dict)) }}
---
{{- include "assistos.configmap-assistos-config" (list . . "" dict) -}}
---
{{- include "assistos.configmap-assistos-apihub-root-config" (list . . "" dict) -}}