{{- if and .Values.docsConverter.enabled .Values.docsConverter.persistence.enabled (not .Values.docsConverter.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-converter
  namespace: {{ template "assistos.namespace" . }}
  labels:
    {{- include "assistos.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs-converter
  {{- with .Values.docsConverter.persistence.finalizers }}
  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.docsConverter.persistence.storageClassName }}
  storageClassName: {{ .Values.docsConverter.persistence.storageClassName }}
  {{- end }}
  accessModes:
    {{- range .Values.docsConverter.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.docsConverter.persistence.size | quote }}
  {{- with .Values.docsConverter.persistence.selectorLabels }}
  selector:
    matchLabels:
      {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
