apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - host: assistos.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assistos
                port:
                  number: 8080
