apiVersion: v1
kind: Service
metadata:
  name: {{ include "assistos.fullname" . }}
  labels:
    {{- include "assistos.labels" . | nindent 4 }}
spec:
{{- if eq .Values.service.assistos.type "LoadBalancer" }}
  {{- if .Values.service.assistos.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.assistos.loadBalancerIP }}
  {{- end }}
  {{- with .Values.service.assistos.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
  type: {{ .Values.service.assistos.type }}
  ports:
    - port: {{ .Values.service.assistos.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "assistos.selectorLabels" . | nindent 4 }}
