apiVersion: v1
kind: Service
metadata:
  name: {{ include "assistos.fullname" . }}
  labels:
    {{- include "assistos.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: assistos-http
  selector:
    {{- include "assistos.selectorLabels" . | nindent 4 }}
